name: Upload artifacts

on:
  push:
    branches:
      - main 

jobs:
  build-project:
    name: Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Upload exe file
        uses: actions/upload-artifact@v4
        with:
          name: myartifact
          path: Tower-Defence-Game/exe

